"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Category = { id: string; name: string };
type Product = { id: string; categoryId: string; name: string; description: string | null; priceAmount: number; available: boolean; published: boolean; featured: boolean; sortOrder: number };

export function ProductForm({ categories, product }: { categories: Category[]; product?: Product }) {
  const router = useRouter();
  const [form, setForm] = useState({ categoryId: product?.categoryId ?? categories[0]?.id ?? "", name: product?.name ?? "", description: product?.description ?? "", priceAmount: String(product?.priceAmount ?? ""), available: product?.available ?? true, published: product?.published ?? true, featured: product?.featured ?? false, sortOrder: String(product?.sortOrder ?? 0) });
  const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  function update<K extends keyof typeof form>(key: K, value: (typeof form)[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); const payload = { ...form, priceAmount: Number(form.priceAmount), sortOrder: Number(form.sortOrder) }; const url = product ? `/api/admin/products/${product.id}` : "/api/admin/products"; const response = await fetch(url, { method: product ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) { const body = await response.json().catch(() => null); setError(body?.message ?? "No se pudo guardar el producto."); setPending(false); return; } const saved = await response.json(); if (file) { const upload = new FormData(); upload.set("productId", saved.id); upload.set("file", file); const uploadResponse = await fetch("/api/admin/media/products", { method: "POST", body: upload }); if (!uploadResponse.ok) { setError("Producto guardado, pero no se pudo subir la imagen. Podés reintentarlo."); setPending(false); return; } } router.push("/admin"); router.refresh(); }
  return <form className="admin-form admin-form--wide" onSubmit={submit}><div className="admin-form-grid"><label>Nombre<input value={form.name} onChange={(event) => update("name", event.target.value)} required /></label><label>Categoría<select value={form.categoryId} onChange={(event) => update("categoryId", event.target.value)} required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Precio ARS<input type="number" min="0" step="1" value={form.priceAmount} onChange={(event) => update("priceAmount", event.target.value)} required /></label><label>Orden<input type="number" min="0" step="1" value={form.sortOrder} onChange={(event) => update("sortOrder", event.target.value)} required /></label></div><label>Descripción<textarea rows={4} value={form.description} onChange={(event) => update("description", event.target.value)} /></label><label>Imagen del producto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><div className="admin-checks"><label><input type="checkbox" checked={form.available} onChange={(event) => update("available", event.target.checked)} /> Disponible</label><label><input type="checkbox" checked={form.published} onChange={(event) => update("published", event.target.checked)} /> Publicado</label><label><input type="checkbox" checked={form.featured} onChange={(event) => update("featured", event.target.checked)} /> Destacado</label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="admin-form-actions"><Link className="admin-button admin-button--secondary" href="/admin">Cancelar</Link><button className="admin-button admin-button--primary" disabled={pending}>{pending ? "Guardando…" : "Guardar producto"}</button></div></form>;
}
